-- setup_snowflake.sql

-- Create compute
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Create database
CREATE DATABASE IF NOT EXISTS STREAMFLOW_DB;

-- Create schema
CREATE SCHEMA IF NOT EXISTS STREAMFLOW_DB.ANALYTICS;

-- Tell Snowflake what to use
USE WAREHOUSE COMPUTE_WH;
USE DATABASE STREAMFLOW_DB;
USE SCHEMA ANALYTICS;